name: pcCapstone
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.4=h60c762c_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - capnproto=1.2.0=hfc315d8_0
  - ceres-solver=2.2.0=gpuhd8f213c_107
  - contourpy=1.3.3=py312hd9148b4_2
  - cpd=0.5.5=h434a139_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - draco=1.5.7=h00ab1b0_0
  - eigen=3.4.0=h171cf75_1
  - fgt=0.4.11=h87365c0_1
  - fmt=12.0.0=h2b0788b_0
  - fonttools=4.60.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - gdal=3.11.4=py312hf50df08_6
  - geos=3.14.0=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - icu=75.1=he02047a_0
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libamd=3.3.3=h456b2da_7100101
  - libarchive=3.8.2=gpl_h7be2006_100
  - libarrow=19.0.1=h85a8487_34_cpu
  - libarrow-acero=19.0.1=h635bf11_34_cpu
  - libarrow-dataset=19.0.1=h635bf11_34_cpu
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libbtf=2.3.2=hf02c80a_7100101
  - libcamd=3.3.3=hf02c80a_7100101
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=37_h0358290_openblas
  - libccolamd=3.3.4=hf02c80a_7100101
  - libcholmod=5.3.1=h9cf07ce_7100101
  - libcolamd=3.3.4=hf02c80a_7100101
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h676940d_1
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libcxsparse=4.4.1=hf02c80a_7100101
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libfabric=2.3.1=ha770c72_0
  - libfabric1=2.3.1=h3ff6011_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgdal-arrow-parquet=3.11.4=hef02800_5
  - libgdal-core=3.11.4=h7321e12_5
  - libgdal-hdf5=3.11.4=h966a9c2_5
  - libgdal-pg=3.11.4=h55c2262_5
  - libgdal-tiledb=3.11.4=h6c35068_5
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h6cb5226_4
  - libklu=2.3.5=h95ff59c_7100101
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.9.0=37_h47877c9_openblas
  - libldl=3.3.2=hf02c80a_7100101
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=19.0.1=h7376487_34_cpu
  - libparu=1.0.0=hc6afc67_7100101
  - libpdal=2.9.2=h260171b_4
  - libpdal-arrow=2.9.2=h95dc5df_4
  - libpdal-core=2.9.2=hbc16f67_4
  - libpdal-cpd=2.9.2=h2e8a393_4
  - libpdal-draco=2.9.2=h2e8a393_4
  - libpdal-e57=2.9.2=h304a8cd_4
  - libpdal-hdf=2.9.2=h01cf3b3_4
  - libpdal-icebridge=2.9.2=h01cf3b3_4
  - libpdal-nitf=2.9.2=h811f341_4
  - libpdal-pgpointcloud=2.9.2=hb16824e_4
  - libpdal-tiledb=2.9.2=h99d2d8e_4
  - libpdal-trajectory=2.9.2=h17d6990_4
  - libpmix=5.0.8=h4bd6b51_2
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - librbio=4.3.4=hf02c80a_7100101
  - libre2-11=2025.08.12=h7b12aa8_1
  - librttopo=1.1.0=h96cd706_19
  - libspatialite=5.1.0=gpl_hcb59c51_118
  - libspex=3.2.3=h9226d62_7100101
  - libspqr=4.3.4=h23b7119_7100101
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsuitesparseconfig=7.10.1=h901830b_7100101
  - libsystemd0=257.9=h996ca69_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=257.9=h085a93f_0
  - libumfpack=6.3.5=h873dde6_7100101
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - matplotlib-base=3.10.7=py312he3d6523_0
  - metis=5.1.0=hd0bcaf9_1007
  - minizip=4.0.10=h05a5f5f_0
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0.1=openmpi
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - ncurses=6.5=h2d0b736_3
  - nitro=2.7.dev8=h59595ed_0
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.3.4=py312h33ff503_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openmpi=5.0.8=h2fe1745_108
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pandoc=3.8.3=ha770c72_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pdal=2.9.2=he64977a_0
  - pip=25.2=pyh8b19718_0
  - postgresql=18.0=hd2008fe_0
  - proj=9.7.0=hb72c0af_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-pdal=3.5.3=np2py312hc4b51ad_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - rdma-core=59.0=hecca717_0
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - s2n=1.5.26=h5ac9029_0
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.16.2=py312h7a1785b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - spdlog=1.16.0=hffee6e0_1
  - sqlite=3.50.4=hbc0de68_0
  - statsmodels=0.14.5=py312h4f23490_1
  - suitesparse=7.10.1=h5b2951e_7100101
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiledb=2.29.1=h59e4f7f_2
  - tk=8.6.13=noxft_hd72426e_102
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h78e105d_0
  - ucc=1.5.1=hb729f83_0
  - ucx=1.19.0=hc93acc0_4
  - unicodedata2=16.0.0=py312h4c3975b_1
  - uriparser=0.9.8=hac33072_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=h988505b_2
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - addict==2.4.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - bokeh==3.8.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - comm==0.2.3
      - configargparse==1.7.1
      - cramjam==2.11.0
      - dash==3.2.0
      - dask==2025.11.0
      - dask-glm==0.3.2
      - dask-ml==2025.1.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distributed==2025.11.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fastparquet==2024.11.0
      - flask==3.1.2
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - ipykernel==7.0.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - lark==1.3.0
      - lckr-jupyterlab-variableinspector==3.2.4
      - llvmlite==0.45.1
      - locket==1.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - msgpack==1.1.2
      - multipledispatch==1.0.0
      - narwhals==2.9.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - open3d==0.19.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - partd==1.4.2
      - pdal-plugins==1.6.6
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - plyfile==1.1.3
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyquaternion==0.9.9
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sparse==0.17.0
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tblib==3.2.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toolz==1.1.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xyzservices==2025.11.0
      - zict==3.0.0
      - zipp==3.23.0
prefix: /home/sspiegel/miniconda3/envs/masterEnv